# Numpy 기초
----
## list 와 Numpy array

In [5]:
x = [[1, 3, 5],
     [2, 4, 6]]
print(x)

[[1, 3, 5], [2, 4, 6]]


## ndarry 생성하기

In [6]:
import numpy as np
x = np.array([[1, 3, 5]
              ,[2, 4, 6]])
print(x)
print(x.mean())

[[1 3 5]
 [2 4 6]]
3.5


In [11]:
list1 = [[1,2,3],[4,5]]
x = np.array(list1)
x

<ipython-input-11-0c71b1089e46>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(list1)


array([list([1, 2, 3]), list([4, 5])], dtype=object)

## ndarray 형태와 차원

In [9]:
x = np.array([1,3,5]) # 1차원
y = np.array([[1,3,5]
              ,[2,4,6]]) # 2차원
y.shape


(2, 3)

##  ndarray 타입

In [12]:
x = np.array([1,2,3])
y = np.array([1.1,2.2,3.3])
z = np.array([True,True,False])
w = np.array(['a','b','c'])
print(x, y, z, w)
print(x.dtype, y.dtype, z.dtype, w.dtype)


[1 2 3] [1.1 2.2 3.3] [ True  True False] ['a' 'b' 'c']
int64 float64 bool <U1


In [15]:
x = np.array([1,2,True])

array(['1', '2', 'a'], dtype='<U21')

## ndarray 타입 설정, 변경

In [57]:
x = np.array([1,2,3], dtype = 'int8')
x = np.array([1,2,3], dtype = 'i1')
x = np.array([1,2,3], dtype = np.int8)

array([1, 2, 3], dtype=int8)

In [18]:
x = np.array([1,2,7])
x = x.astype('int8')
x


array([1, 2, 7], dtype=int8)

## ndarray 형태 살펴보기

In [36]:
x = np.array([1,2,3])
y = np.array([[1,2,3],
              [4,5,6]])
z = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
            [[10,11,12],
             [13,14,15],
             [16,17,18]]])
z[0][0][2]
# print(x.shape, y.shape, z.shape)

3

## 지금까지 배운 numpy 여러가지 method들



In [41]:
x = np.array([[1,2,3],
              [4,5,6]])
x.mean(axis=1)

array([2., 5.])

In [49]:
x = np.array([[1,2,3],
              [4,5,6]])
print(x, x.shape)
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
y = x.reshape(2,2,2,2)
print(y, y.shape)
y.mean(axis=1)

[[1 2 3]
 [4 5 6]] (2, 3)
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]] (2, 2, 2, 2)


array([[[ 3.,  4.],
        [ 5.,  6.]],

       [[11., 12.],
        [13., 14.]]])

In [54]:
a = np.ones((2,3,3,3))
a

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

#### 추가

In [56]:
a = np.arange(5,80)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79])

## Numpy Slicing

### 1차원 ndarray Slicing

In [101]:
x = np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
x[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [104]:
x[5:]

array([1, 2, 3, 4, 5])

In [105]:
x[2:7]

array([3, 4, 5, 6, 7])

In [108]:
x[::2]

array([1, 3, 5, 7, 9])

In [112]:
x[1::2]

array([2, 4, 6, 8])

### 2차원 ndarray Slicing

In [59]:
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
x[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
x[:2,1]

array([2, 5])

In [96]:
x[1,:]

array([4, 5, 6])

In [99]:
x[:,1]

array([2, 5, 8])

In [100]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

### 5x5의 2차원 ndarray를 생성하고 2번째 행만 출력해보기

In [80]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
a=1
y = x[2]
x[1,:]
z = x[2:2+a]
print(y, z)

[11 12 13 14 15] [[11 12 13 14 15]]


### 5x5의 2차원 ndarray를 생성하고 2번째 열만 출력해보기

In [89]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
x[:,1]
x[0:,1]
x[:,1:2].reshape(5)

array([ 2,  7, 12, 17, 22])

### 5x5의 2차원 ndarray를 생성하고 2,3번째 행의 4,5번째 열 출력해보기

In [86]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])
x[1:3,3:]
x[1:3,3:5]

array([[ 9, 10],
       [14, 15]])

## Numpy 연산

In [32]:
import math
math.sqrt(2)

1.4142135623730951

In [116]:
x = [1,2,3]
math.sqrt(x)

TypeError: must be real number, not list

In [3]:
x = [1]
math.sqrt(x)

TypeError: must be real number, not list

## list에서 math.sqrt 계산 시키기

In [33]:
x = [1,2,3]
y = []
for i in x:
    y.append(math.sqrt(i))
print(y)

[1.0, 1.4142135623730951, 1.7320508075688772]


In [34]:
x = np.array([1,2,3])
math.sqrt(x)

TypeError: only size-1 arrays can be converted to Python scalars

In [119]:
x = np.array([1])
math.sqrt(x)

1.0

In [120]:
x = [1,2,3]
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [122]:
x = np.array([1,2,3])
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

## 제로 벡터, 제로 행렬 만들기

In [131]:
x = np.zeros(2)
x

array([0., 0.])

In [35]:
x = np.zeros(3, 4)
x

TypeError: Cannot interpret '4' as a data type

In [38]:
x = np.zeros([3,5,2], )
x

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
x = np.zeros((3,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 1로 이루어진 벡터, 행렬 만들기

In [137]:
x = np.ones(2)
x

array([1., 1.])

In [138]:
x = np.ones(2,3)

TypeError: Cannot interpret '3' as a data type

In [139]:
x = np.ones([4,6])
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 전치 행렬 

### for문을 이용해서 전치 행렬 만들어보기
    1 2 3    1 4 7  
    4 5 6 -> 2 5 8  
    7 8 9    3 6 9

In [39]:
import numpy as np

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
y = np.zeros([3,3])

for i in range(3):
    for j in range(3):
        y[i,j] = x[j,i]
y




array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [49]:
import numpy as np

x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

y = np.zeros(x.shape).reshape(3,4)
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np method 사용해서 전치 행렬 만들길

In [140]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [141]:
x.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [142]:
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 사칙연산

In [55]:
x = np.array([1,2,3])
y = np.array([5,6])
x*y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [50]:
x = np.array([[1,2,3],
              [4,3,2]])
y = np.array([[0,4,2],
              [1,2,8]])
x+y

array([[ 1,  6,  5],
       [ 5,  5, 10]])

In [58]:
x * 2

array([2, 4, 6])

### 십의자리 수(0~9)를 입력 받아 숫자 출력하기
+ ex) 8입력 -> [80 81 82 83 84 85 86 87 88 89] 출력

In [59]:
x = np.array([0,1,2,3,4,5,6,7,8,9])
ten_num = int(input("십의 자리를 입력하세요. : "))
x = x + 10 * ten_num
print(x)






십의 자리를 입력하세요. : 3
[30 31 32 33 34 35 36 37 38 39]


In [144]:
x*y

array([ 5, 12, 21])

### 구구단 단수 입력 받아 출력하기

In [145]:
x-y

array([-4, -4, -4])

In [147]:
x = np.array([1,2,3])
y = np.array([1,2])
x+y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## 인덱싱

In [62]:
x = np.array([[1,2,3,4],
            [5,6,7,8],
              [9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
x[1]

array([5, 6, 7, 8])

In [64]:
x[:,1]

array([ 2,  6, 10])

In [65]:
x[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [152]:
x[:,[1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [161]:
x = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
x[1,:], x


(array([5, 6, 7, 8]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [16]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = [1,5,8]
a[b]

array([2, 6, 9])

In [67]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a[1:5:2]
print('b:', b)
b[1] = 10
print('b:', b)
print('a:', a)

b: [20 40]
b: [20 10]
a: [10 20 30 10 50 60 70]


## 불리언

In [18]:
a = np.array([10, 20, 30, 40, 50, 60, 70])
b = a > 50
print(b)

[False False False False False  True  True]


### 시험점수가 40점 이하는 0점으로 처리하고 40점 초과만 점수 그대로 적용해보기

In [69]:
score = np.array([30,50,46,25,83,42,21,68,92])
more40 = score > 40
more40 * score

array([ 0, 50, 46,  0, 83, 42,  0, 68, 92])

### 시험점수 40점 초과는 10점 추가점수 부여

In [76]:
score = np.array([30,50,46,25,83,42,21,68,92])
more40 = score > 40
new_score = score + more40 * 10
print(new_score)
less100 = new_score <= 100
print(less100)
more100 = new_score > 100
print(more100)
final_score = new_score * less100 + 100 * more100
print(final_score)

[ 30  60  56  25  93  52  21  78 102]
[ True  True  True  True  True  True  True  True False]
[False False False False False False False False  True]
[ 30  60  56  25  93  52  21  78 100]


In [79]:
score = np.array([30,50,46,25,83,42,21,68,92])
all40 = np.all(score>40)
or40 = np.any(score>40)
all40
or40

True

## 랜덤

In [80]:
ary = np.random.random(5)
ary

array([0.72415441, 0.06421973, 0.76344965, 0.38223868, 0.50867021])

In [83]:
ary2 = np.random.random([2,3])
ary2

array([[0.65675099, 0.76625558, 0.72245882],
       [0.10249946, 0.910761  , 0.9043933 ]])

In [20]:
print(np.all(ary >= 0.3))

False


In [21]:
print(np.any(ary > 0.7))

True


## 등간격 나누기

In [85]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [86]:
np.linspace(0, 12, 5)

array([ 0.,  3.,  6.,  9., 12.])

In [88]:
np.linspace(5, 53, 11, retstep=True)

(array([ 5. ,  9.8, 14.6, 19.4, 24.2, 29. , 33.8, 38.6, 43.4, 48.2, 53. ]),
 4.8)

In [90]:
np.linspace(0, 65, 7, endpoint=False)

array([ 0.        ,  9.28571429, 18.57142857, 27.85714286, 37.14285714,
       46.42857143, 55.71428571])

In [91]:
1 - 2
1, 1.25, 1.5, 1,75, 2

(1, 1.25, 1.5, 1, 75, 2)

In [95]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[2,3],
              [4,5]])
print(a,'\n',b)
np.matmul(a,b)

[[1 2]
 [3 4]] 
 [[2 3]
 [4 5]]


array([[10, 13],
       [22, 29]])

In [97]:
a = np.array([[1,2],
              [2,3],
              [3,4],
              [4,5]])
b = np.array([2,1])
np.matmul(a,b)
# [a,b] [b,c] -> [a,c]

array([ 4,  7, 10, 13])

In [171]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [174]:
np.log10(10), np.log(100)

(1.0, 4.605170185988092)

In [99]:
np.logspace(2, 6, 5)
# np.linspace(2, 6, 5)

array([1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06])

In [178]:
10**1.25, 10**1.5, 10**1.75

(17.78279410038923, 31.622776601683793, 56.23413251903491)

## Numpy 난수 생성
### random.rand() - [0.0, 1.0) 에서 균일한 분포를 가지는 난수를 반환

In [31]:
a = np.random.rand(5)
a

array([0.79535031, 0.76711264, 0.52447721, 0.7293213 , 0.32543609])

In [100]:
a = np.random.rand(2,3,3)
a

array([[[0.38558567, 0.70026096, 0.75105639],
        [0.65014689, 0.773043  , 0.71343233],
        [0.28924947, 0.90823362, 0.44084764]],

       [[0.81725376, 0.12003444, 0.04663409],
        [0.78122346, 0.88479879, 0.9870573 ],
        [0.63421807, 0.76018989, 0.26054215]]])

### random.randint() - 특정범위의 정수를 난수로 반환

In [185]:
a = np.random.randint(4, size = 5)
a

array([2, 2, 2, 3, 2])

In [187]:
a = np.random.randint(2,5, size = 5)
a

array([2, 3, 3, 2, 4])

In [22]:
a = np.random.randint(1,5, size = (2,5))
a

array([[1, 2, 1, 4, 1],
       [4, 2, 4, 1, 4]])

### random.randn() - 표준정규분포에 의해 난수를 반환

In [192]:
a = np.random.randn(5)
a

array([-0.2897138 , -0.35063673, -0.24699327,  0.0743073 ,  0.54602196])

In [108]:
a = np.random.rand(2,3,2)
a

array([[[0.7958169 , 0.95259296],
        [0.04320596, 0.53412518],
        [0.49210288, 0.31629804]],

       [[0.90295327, 0.85930093],
        [0.05162815, 0.62512052],
        [0.17880118, 0.56584146]]])

### random.standard_normal() - 표준정규분포에 의한 난수를 반환 (튜플 사용)

In [194]:
a = np.random.standard_normal(3)
a

array([-1.72120797,  0.67309822, -1.9967577 ])

In [195]:
a = np.random.standard_normal(2,3)

TypeError: standard_normal() takes at most 1 positional argument (2 given)

In [196]:
a = np.random.standard_normal((2,3))
a

array([[-0.22711118, -0.33976461, -1.11240489],
       [-0.551868  ,  1.06581371, -0.11983732]])

### random.normal() - 정규분포에 의한 난수를 반환

In [198]:
a = np.random.normal(0,1,2)
a

array([0.01074844, 0.45790191])

In [199]:
a = np.random.normal(0, 10, 5)
a

array([-11.17622906,   3.72751561,   5.06631201,  -1.87694458,
         8.5540818 ])

In [200]:
a = np.random.normal(5,2,(2,3))
a

array([[0.47694563, 3.78468993, 7.91359081],
       [1.14510038, 4.68765211, 5.6868828 ]])

### random.random_sample() - [0.0, 1.0) 범위의 임의의 실수 반환

In [202]:
a = np.random.random_sample(2)
a

array([0.2097915 , 0.71534024])

In [204]:
a = np.random.random_sample((2,5))
a

array([[0.14006396, 0.81616232, 0.16852466, 0.41816908, 0.24721263],
       [0.42968153, 0.8398507 , 0.5797957 , 0.65666028, 0.44329283]])

### random.choice() - 주어진 1차원 array에서 난수를 반환

In [109]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [211]:
a = np.random.choice(10, 5)
a

array([5, 1, 5, 8, 2])

In [213]:
a = np.random.choice(10, (2,3))
a

array([[4, 5, 8],
       [3, 0, 6]])

In [110]:
a = np.random.choice([2,4,6,8], 10)
a

array([6, 8, 2, 2, 4, 2, 6, 6, 6, 6])

### random.seed() - 난수 생성에 필요한 시드 설정

In [127]:
np.random.seed(5)

np.random.randn(5)


array([ 0.44122749, -0.33087015,  2.43077119, -0.25209213,  0.10960984])