In [173]:
import numpy as np
a = np.array([1,2,3])
a[1]

2

In [175]:
import pandas as pd
a = pd.Series([7, 3, 5, 8])
a[0]

7

#### index

In [191]:
x = pd.Series([7, 3, 5, 8], index=['서울', '대구', '부산', '광주'])
# x.index.name="지역"
print(x)
print(x['서울'])


서울    7
대구    3
부산    5
광주    8
dtype: int64
7


In [143]:
x[['서울', '대구']]

서울    7
대구    3
dtype: int64

In [17]:
x.index

Index(['서울', '대구', '부산', '광주'], dtype='object')

In [18]:
x.values

array([7, 3, 5, 8])

#### Series의 값으로 문자열 넣어보기
+ 족발 - 보쌈
+ 허니콤보 - 엽떡
+ 짜장면 - 파김치
+ 파스타 - 피자

In [183]:
x = pd.Series(['보쌈', '엽떡', '파김치', '피자'], index=['족발','허니콤보','짜장면','파스타'])
x

족발       보쌈
허니콤보     엽떡
짜장면     파김치
파스타      피자
dtype: object

#### sorted()

In [19]:
print(sorted(x))

[3, 5, 7, 8]


In [148]:
print(sorted(x.index))

['광주', '대구', '부산', '서울']


In [6]:
sorted(x.values)

[3, 5, 7, 8]

In [7]:
x.reindex(sorted(x.index)) # 인덱스 순서에 따라 다시 정렬

광주    8
대구    3
부산    5
서울    7
dtype: int64

#### reindex를 사용해서 [서울 부산 대구 광주] 순서로 정렬해보기

In [193]:
y = x.reindex(['서울','부산','대구','광주'])
x

서울    7
대구    3
부산    5
광주    8
dtype: int64

#### index에 제주를 넣고 [서울 부산 대구 광주 제주] 순서로 정렬해보기

In [187]:
x.reindex(['서울','부산','대구','광주','제주'])

서울    7.0
부산    5.0
대구    3.0
광주    8.0
제주    NaN
dtype: float64

#### index가 '제주'인 새로운 데이터를 넣어보고 [서울 부산 대구 광주 제주] 순서로 정렬해보기

In [188]:
x['제주'] = 10
x

서울     7
대구     3
부산     5
광주     8
제주    10
dtype: int64

#### 인덱스별로 저장된 값들의 합을 구하기

In [204]:
x = pd.Series([3, 8, 5, 9], index=['서울', '대구', '부산', '광주'])
y = pd.Series([2, 4, 5, 1], index=['대구', '부산', '서울', '광주'])
x+y

광주    10
대구    10
부산     9
서울     8
dtype: int64

#### 문자열로 이루어진 시리즈 합 구해보기
+ 족발 - 보쌈, 막국수
+ 허니콤보 - 엽떡, 배떡
+ 짜장면 - 파김치, 탕수육
+ 파스타 - 피자, 피클

In [207]:
x = pd.Series([1,2,3,4], index=['족발','허니콤보','짜장면','파스타'])
y = pd.Series(['막국수','배떡','탕수육','피클'], index=['족발','허니콤보','짜장면','파스타'])
x+y

TypeError: unsupported operand type(s) for +: 'int' and 'str'

#### unique()

In [208]:
medal = [1, 3, 2, 4, 2, 3]
x = pd.Series(medal)
print(x)
print(pd.unique(x))


0    1
1    3
2    2
3    4
4    2
5    3
dtype: int64
[1 3 2 4]


In [36]:
medal = ['민준', '현우', '서연', '동현', '서연', '현우']
x = pd.Series(medal)
print(pd.unique(x))

['민준' '현우' '서연' '동현']


#### 사전 형식의 데이터를 Pandas의 Series 형식으로 변환

In [210]:
age = {'민준':23, '현우':43, '서연':12, '동현':45}
x = pd.Series(age)
print(x)
print(x.index)
print(x.values)

민준    23
현우    43
서연    12
동현    45
dtype: int64
Index(['민준', '현우', '서연', '동현'], dtype='object')
[23 43 12 45]


In [216]:
names = ['민준', '서연', '현우', '민서', '동현', '수빈']
pdata = pd.Series(names)
a = names[3:6]
a[0]

'민서'

In [219]:
a = pdata[3:6]
print(a[3])

민서


### 데이터프레임
#### 딕셔너리 형태로 만들기

In [230]:
data = {'age' : [23, 43, 12, 45],
       'name' : ['민준', '현우', '서연', '동현'],
       'height' : [175.3, 180.3, 165.8, 172.7]}
x = pd.DataFrame(data, columns = ['name', 'age', 'height'])
x.index.name="출석번호"
x.columns.name='신상정보'
x

신상정보 name  age  height
출석번호                  
0      민준   23   175.3
1      현우   43   180.3
2      서연   12   165.8
3      동현   45   172.7

#### name 컬럼의 내용만 출력

In [125]:
x.name

0    민준
1    현우
2    서연
3    동현
Name: name, dtype: object

In [235]:
x[:]['name']

출석번호
0    민준
1    현우
2    서연
3    동현
Name: name, dtype: object

In [233]:
x[0]

KeyError: 0

#### iloc()

In [237]:
ary = [[1, 2],
       [3, 4],
       [5, 6]]
data = pd.DataFrame(ary, columns=['First', 'Second'], index=[10,20,30])
data

First  Second
10      1       2
20      3       4
30      5       6

In [238]:
data.iloc[1]

First     3
Second    4
Name: 20, dtype: int64

In [239]:
data.iloc[:, -1]

10    2
20    4
30    6
Name: Second, dtype: int64

In [244]:
ary = [[1,2,3,4,5],
      [6,7,8,9,10],
      [11,12,13,14,15],
      [16,17,18,19,20]]
data = pd.DataFrame(ary, columns=['First', 'Second', 'Third', 'Fourth', 'Fifth'], index=[1,2,3,4])
data

First  Second  Third  Fourth  Fifth
1      1       2      3       4      5
2      6       7      8       9     10
3     11      12     13      14     15
4     16      17     18      19     20

#### iloc을 이용해서 2,3 번째 column만 뽑아보기

In [245]:
data.iloc[:,1:3]

Second  Third
1       2      3
2       7      8
3      12     13
4      17     18

#### iloc을 이용해서 2,3 번째 index만 뽑아보기

In [246]:
data.iloc[1:3]

First  Second  Third  Fourth  Fifth
2      6       7      8       9     10
3     11      12     13      14     15

#### iloc을 이용해서 2,3 번째 column의 3,4번째 index만 뽑아보기

In [247]:
data.iloc[2:4,1:3]

Second  Third
3      12     13
4      17     18

#### loc() - index와 column의 이름으로 출력하기

In [249]:
ary = [[1, 2],
       [3, 4],
       [5, 6]]
data = pd.DataFrame(ary, columns=['First', 'Second'], index=['one','two','three'])
data

First  Second
one        1       2
two        3       4
three      5       6

In [70]:
data.loc['one']

First     1
Second    2
Name: one, dtype: int64

In [72]:
data.loc[:,'First']

one      1
two      3
three    5
Name: First, dtype: int64

In [250]:
data.loc['one':'three','First':'Second']

First  Second
one        1       2
two        3       4
three      5       6

In [251]:
ary = [[1,2,3,4,5],
      [6,7,8,9,10],
      [11,12,13,14,15],
      [16,17,18,19,20]]
data = pd.DataFrame(ary, columns=['First', 'Second', 'Third', 'Fourth', 'Fifth'], index=['one','two','three','four'])
data

First  Second  Third  Fourth  Fifth
one        1       2      3       4      5
two        6       7      8       9     10
three     11      12     13      14     15
four      16      17     18      19     20

#### loc()을 사용해서 2,3 번째 index만 출력해보기

In [253]:
data.loc[['two','three']]

First  Second  Third  Fourth  Fifth
two        6       7      8       9     10
three     11      12     13      14     15

#### loc()을 사용해서 3,4,5 번째 column만 출력해보기

In [254]:
data.loc[:,'Third':'Fifth']

Third  Fourth  Fifth
one        3       4      5
two        8       9     10
three     13      14     15
four      18      19     20

#### loc()을 사용해서 1,4번째 index의 2,4,5 column만 출력해보기

In [256]:
data.loc[['one','four'],['Second','Fourth','Fifth']]

Second  Fourth  Fifth
one        2       4      5
four      17      19     20

#### head()와 tail()

In [260]:
ary = [[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 10]]
data = pd.DataFrame(ary, columns=['First', 'Second'])
data
data.head(4)

First  Second
0      1       2
1      3       4
2      5       6
3      7       8

In [261]:
data.tail(3)

First  Second
2      5       6
3      7       8
4      9      10

#### 특정 항목만 선택

In [263]:
print(data)
bools = [False, True, True, False, True]
data[bools]

   First  Second
0      1       2
1      3       4
2      5       6
3      7       8
4      9      10


First  Second
1      3       4
2      5       6
4      9      10

#### 수학적인 메소드를 이용하여 계산

In [273]:
data = {'age' : [23, 43, 12, 45],
       'name' : ['민준', '현우', '서연', '동현'],
       'height' : [175.3, 180.3, 165.8, 172.7]}
x = pd.DataFrame(data, columns = ['name', 'age', 'height'])
print(x)
print(x.mean(axis=0)) #max, min, sum

  name  age  height
0   민준   23   175.3
1   현우   43   180.3
2   서연   12   165.8
3   동현   45   172.7
age        30.750
height    173.525
dtype: float64


## Pandas 데이터의 형변환

In [275]:
import pandas as pd
#import numpy as np
ary = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
data = pd.DataFrame(ary, columns=['First', 'Second'], index = ['a','b','c','d','e'])
data

First  Second
a      1       2
b      3       4
c      5       6
d      7       8
e      9      10

In [276]:
data['First'] = data['First'].astype('float')
data.astype('float')

First  Second
a    1.0     2.0
b    3.0     4.0
c    5.0     6.0
d    7.0     8.0
e    9.0    10.0

### Pandas에 파일 가져오기

In [279]:
import pandas as pd
data = pd.read_csv('FL_insurance_sample.csv')
data.head(10)

policyID statecode       county  eq_site_limit  hu_site_limit  \
0    119736        FL  CLAY COUNTY       498960.0      498960.00   
1    448094        FL  CLAY COUNTY      1322376.3     1322376.30   
2    206893        FL  CLAY COUNTY       190724.4      190724.40   
3    333743        FL  CLAY COUNTY            0.0       79520.76   
4    172534        FL  CLAY COUNTY            0.0      254281.50   
5    785275        FL  CLAY COUNTY            0.0      515035.62   
6    995932        FL  CLAY COUNTY            0.0    19260000.00   
7    223488        FL  CLAY COUNTY       328500.0      328500.00   
8    433512        FL  CLAY COUNTY       315000.0      315000.00   
9    142071        FL  CLAY COUNTY       705600.0      705600.00   

   fl_site_limit  fr_site_limit     tiv_2011     tiv_2012  eq_site_deductible  \
0       498960.0       498960.0    498960.00    792148.90                 0.0   
1      1322376.3      1322376.3   1322376.30   1438163.57                 0.0   
2       190724.4       190724.4    190724.40    192476.78                 0.0   
3            0.0            0.0     79520.76     86854.48                 0.0   
4            0.0       254281.5    254281.50    246144.49                 0.0   
5            0.0            0.0    515035.62    884419.17                 0.0   
6            0.0            0.0  19260000.00  20610000.00                 0.0   
7       328500.0       328500.0    328500.00    348374.25                 0.0   
8       315000.0       315000.0    315000.00    265821.57                 0.0   
9       705600.0       705600.0    705600.00   1010842.56             14112.0   

   hu_site_deductible  fl_site_deductible  fr_site_deductible  point_latitude  \
0              9979.2                 0.0                   0       30.102261   
1                 0.0                 0.0                   0       30.063936   
2                 0.0                 0.0                   0       30.089579   
3                 0.0                 0.0                   0       30.063236   
4                 0.0                 0.0                   0       30.060614   
5                 0.0                 0.0                   0       30.063236   
6                 0.0                 0.0                   0       30.102226   
7             16425.0                 0.0                   0       30.102217   
8             15750.0                 0.0                   0       30.118774   
9             35280.0                 0.0                   0       30.100628   

   point_longitude         line         construction  point_granularity  
0       -81.711777  Residential              Masonry                  1  
1       -81.707664  Residential              Masonry                  3  
2       -81.700455  Residential                 Wood                  1  
3       -81.707703  Residential                 Wood                  3  
4       -81.702675  Residential                 Wood                  1  
5       -81.707703  Residential              Masonry                  3  
6       -81.713882   Commercial  Reinforced Concrete                  1  
7       -81.707146  Residential                 Wood                  1  
8       -81.704613  Residential                 Wood                  1  
9       -81.703751  Residential              Masonry                  1